<?php
return [
    'title' => 'Контакти',
    'navPhone' => 'Загальний номер',
    'navSalesDepartment' => 'Відділ продажів',
    'navShops' => 'Магазини',
    'navSupport' => 'Техпідтримка',
    'navAccounting' => 'Бухгалтерія',
    'sharedRoom' => 'Загальний номер',
    'sharedRoomSchedule' => 'Багатоканальний телефон гарячої лінії. Звертайтеся з понеділка по п"ятницю 9.00 - 17.30',
    'freeCalls' => '(безплатні дзвінки з мобільних і стаціонарних телефонів у межах України)',
    'weAreGlad' => 'Ми завжди раді відповісти на Ваші питання через соціальні мережі!',
    'callCentre' => 'Call-центер, ввіділ роздрібної торгівлі',
    'cheltsovaIrina' => 'Чельцова Ірина',
    'headOfRetailDepartmen' => 'Керівник роздрібного відділу',
    'annaGeorgieva' => 'Анна Георгієва',
    'managerRetailDepartment' => 'Менеджер розничного отдела продаж',
    'burakovaAlexandra' => 'Буракова Олександра',
    'lototskyVyacheslav' => 'Лотоцький Вячеслав',
    'belokurVladislav' => 'Білокур Владислав',
    'tokarevAlexander' => 'Токарев Олександр',
    'wholesaleSalesDepatrment' => 'Відділ оптової торгівлі',
    'olegKremeniuk' => 'Олег Кременюк',
    'wholesaleSalesManager' => 'Менеджер оптового відділу продажу',
    'igorKremenyuk' => 'Ігор Кременюк',
    'popovaAnastasia' => 'Попова Анастасія',
    'lozitskayaValeria' => 'Лозіцька Валерія',
    'tsybriyMaxim' => 'Цыбрий Максим',
];