<?php
return [
    'title' => 'Контакты',
    'navPhone' => 'Общий номер',
    'navSalesDepartment' => 'Отдел продаж',
    'navShops' => 'Магазины',
    'navSupport' => 'Техподдержка',
    'navAccounting' => 'Бухгалтерия',
    'sharedRoom' => 'Общий номер',
    'sharedRoomSchedule' => 'Многоканальный телефон горячей линии. Обращаться понедельник - пятница с 9.00 до 17.30',
    'freeCalls' => '(звонки с мобильных и стационарных телефонов в пределах Украины бесплатные)',
    'weAreGlad' => 'Мы всегда рады ответить на вопросы в социальных сетях!',
    'callCentre' => 'Call-центер, отдел розничной торговли',
    'cheltsovaIrina' => 'Чельцова Ирина',
    'headOfRetailDepartmen' => 'Руководитель розничного отдела',
    'annaGeorgieva' => 'Анна Георгиева',
    'managerRetailDepartment' => 'Менеджер розничного отдела продаж',
    'burakovaAlexandra' => 'Буракова Александра',
    'lototskyVyacheslav' => 'Лотоцкий Вячеслав',
    'belokurVladislav' => 'Белокур Владислав',
    'tokarevAlexander' => 'Токарев Александр',
    'wholesaleSalesDepatrment' => 'Оптовый Отдел продаж',
    'olegKremeniuk' => 'Олег Кременюк',
    'wholesaleSalesManager' => 'Менеджер оптового отдела продаж',
    'igorKremenyuk' => 'Игорь Кременюк',
    'popovaAnastasia' => 'Попова Анастасия',
    'lozitskayaValeria' => 'Лозицкая Валерия',
    'tsybriyMaxim' => 'Цыбрий Максим',
];